const LOAD_TRANSLATIONS = 'LOAD_TRANSLATIONS';
const SET_DEFAULT_LANGUAGE = 'SET_DEFAULT_LANGUAGE';
const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const GET_LIST_PRODUCT_REQUESTED = 'GET_LIST_PRODUCT_REQUESTED';
const GET_LIST_PRODUCT_SUCCEEDED = 'GET_LIST_PRODUCT_SUCCEEDED';
const GET_LIST_PRODUCT_FAILED = 'GET_LIST_PRODUCT_FAILED';

export const ACTION_TYPES = {
  LOAD_TRANSLATIONS,
  SET_DEFAULT_LANGUAGE,
  CHANGE_LANGUAGE,
  GET_LIST_PRODUCT_REQUESTED,
  GET_LIST_PRODUCT_SUCCEEDED,
  GET_LIST_PRODUCT_FAILED
};
